__BASE__: [
  '../coco.yaml',
  './hyp.scratch.mlx.yaml',
  './yolov11-base.yaml'
]

overflow_still_update: False
network:
  depth_multiple: 0.50  # scales module repeats
  width_multiple: 1.00  # scales convolution channels
  max_channels: 512
