__BASE__: [
  '../coco.yaml',
  './hyp.scratch.xp6.yaml',
  './yolov8p6-base.yaml'
]

overflow_still_update: False
network:
  depth_multiple: 1.00  # scales module repeats
  width_multiple: 1.25  # scales convolution channels
  max_channels: 512
