epochs: 500  # total train epochs
per_batch_size: 8
img_size: 1280
iou_thres: 0.7
conf_free: True
sync_bn: True
anchor_base: False
opencv_threads_num: 0  # opencv: disable threading optimizations

network:
  model_name: yolov8
  nc: 80  # number of classes
  reg_max: 16

  stride: [8, 16, 32, 64]

  # YOLOv8.0n backbone
  backbone:
    # [from, repeats, module, args]
    - [-1, 1, ConvNormAct, [64, 3, 2]]  # 0-P1/2
    - [-1, 1, ConvNormAct, [128, 3, 2]]  # 1-P2/4
    - [-1, 3, C2f, [128, True]]
    - [-1, 1, ConvNormAct, [256, 3, 2]]  # 3-P3/8
    - [-1, 6, C2f, [256, True]]
    - [-1, 1, ConvNormAct, [512, 3, 2]]  # 5-P4/16
    - [-1, 6, C2f, [512, True]]
    - [-1, 1, ConvNormAct, [768, 3, 2]] # 7-P5/32
    - [-1, 3, C2f, [768, True]]
    - [-1, 1, ConvNormAct, [1024, 3, 2]]  # 9-P6/64
    - [-1, 3, C2f, [1024, True]]
    - [-1, 1, SPPF, [1024, 5]]  # 11

  # YOLOv8.0n6 head
  head:
    - [-1, 1, Upsample, [None, 2, 'nearest']]
    - [[-1, 8], 1, Concat, [1]]  # cat backbone P5
    - [-1, 3, C2, [768, False]]  # 14

    - [-1, 1, Upsample, [None, 2, "nearest"]]
    - [[-1, 6], 1, Concat, [1]] # cat backbone P4
    - [-1, 3, C2, [512, False]] # 17
    
    - [-1, 1, Upsample, [None, 2, 'nearest']]
    - [[-1, 4], 1, Concat, [1] ]  # cat backbone P3
    - [-1, 3, C2, [256, False]]  # 20 (P3/8-small)

    - [-1, 1, ConvNormAct, [256, 3, 2]]
    - [[ -1, 17], 1, Concat, [1]]  # cat head P4
    - [-1, 3, C2, [512, False]]  # 23 (P4/16-medium)

    - [-1, 1, ConvNormAct, [512, 3, 2]]
    - [[-1, 14], 1, Concat, [1]] # cat head P5
    - [-1, 3, C2, [768, False]] # 26 (P5/32-large)

    - [-1, 1, ConvNormAct, [768, 3, 2]]
    - [[-1, 11], 1, Concat, [1]]  # cat head P5
    - [-1, 3, C2, [1024, False]]  # 21 (P5/32-large)

    - [[20, 23, 26, 29], 1, YOLOv8Head, [nc, reg_max, stride]]  # Detect(P3, P4, P5, P6)
